NAME		= FragTrap
CC			= c++
CFLAGS		= -Wall -Wextra -Werror

SRCS		= main.cpp ClapTrap.cpp FragTrap.cpp
OBJS		= $(SRCS:.cpp=.o)

all:		$(NAME)

$(NAME):	$(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(NAME)

%.o:		%.cpp
	${CC} ${CFLAGS} -c $< -o $@

clean:
	rm -rf $(OBJS)

fclean:		clean
	rm -rf $(NAME)

re: fclean all

.PHONY: all clean fclean re
